name: ClangFormat Linter

on:
  push:
    branches:
      - dev
      - CICD

jobs:
  clang-format-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run ClangFormat Linter
      uses: DoozyX/clang-format-lint-action@v0.13
      with:
        source: '.'
        clangFormatVersion: 11
        command: |
          -style=file
          -i