name: ClangFormat Linter

on:
  push:
    branches-ignore:
      - dev
      - client
      - server
      - game-engine
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Check if on a branch"
      run: |
        if [[ "${{ github.ref }}" != refs/heads/* ]]; then
          echo "Not on a branch, skipping job."
          exit 78
        fi
    - uses: actions/checkout@v2
    - name: "Install clang-format"
      run: sudo apt-get install -y clang-format
    - name: "Run clang-format"
      run: find . -iname '*.hpp' -o -iname '*.cpp' ! -path "./build/*" | xargs clang-format -i -style=file
    - uses: EndBug/add-and-commit@v9
      with:
        author_name: Clang Robot
        author_email: robot@example.com
        message: 'style (*): Committing clang-format changes'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}